<?php
/**
 * @user: Pawel Babilas
 * @date: 04.01.2016
 */

namespace app\common\widgets;


use app\module\module\models\Module;
use Yii;
use yii\base\Widget;
use yii\helpers\Html;
use yii\web\User;

class Menu extends Widget
{
	/**
	 * [
	 * 	categoryName => Modules[]
	 * ]
	 * @var array
	 */
	public $itemsList = [];

	/** @var string  */
	public $defaultIcon = 'hashtag';

	/** @var string  */
	public $defaultClassName = 'nav sidebar-menu';

	/** @var array  */
	public $options = [];

	/** @var string */
	private $controllerName;
	/** @var string */
	private $moduleName;

	/** @var  User */
	private $user;

	public function init()
	{
		$this->controllerName = Yii::$app->controller->id;
		$this->moduleName = Yii::$app->controller->module->id;
		$this->user = Yii::$app->getUser();
		parent::init(); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
	public function run()
	{
		$li = [];

		/**
		 * @var string $categoryName
		 * @var array $modules
		 */
		foreach ($this->itemsList as $categoryName => $modules)
		{
			$li[] = Html::tag('li', $categoryName, ['class' => 'header']);

			$hasAnyItem = false;
			/** @var Module $module */
			foreach ($modules as $module)
			{
				$modulePermissionName = sprintf('access%s', ucfirst($module->name));
				if ($this->user->can($modulePermissionName) == false)
				{
					continue;
				}

				$hasAnyItem = true;

				if ($controllers = $module->getAdminControllers())
				{
					$isActive = $this->moduleName == $module->name;
					$aContent = [];
					if (count($controllers) > 1)
					{
						$aContent[] = Html::tag('i', '', ['class' => sprintf('fa fa-%s', $module->icon)]);
						$aContent[] = Html::tag('span', $module->long_name);
						$aContent[] = Html::tag('i', '', ['class' => 'fa fa-angle-left pull-right']);
						$a = Html::tag('a', join("\n", $aContent), ['href' => '#']);
						$optionsMain = $isActive ? ['class' => 'treeview active'] : ['class' => 'treeview'];

						$li_2 = [];
						foreach ($controllers as $controller)
						{
							$isActive = $this->moduleName == $module->name && $this->controllerName == $controller;
							$icon = Html::tag('i', '', ['class' => 'fa fa-circle-o']);
							$aContent2 = sprintf('%s `%s.%s`', $icon, $module->name, $controller);
							$a2 = Html::tag('a', $aContent2, ['href' => sprintf('/admin/%s/%s', $module->name, $controller)]);
							$options = $isActive ? ['class' => 'active'] : [];
							$li_2[] = Html::tag('li', $a2, $options);
						}

						$ul_2 = Html::ul($li_2, ['class' => 'treeview-menu', 'encode' => false]);
						$li[] = Html::tag('li', $a . "\n" . $ul_2, $optionsMain);
					}
					else
					{
						$aContent[] = Html::tag('i', '', ['class' => sprintf('fa fa-%s', $module->icon)]);
						$aContent[] = Html::tag('span', $module->long_name);
						$a = Html::tag('a', join("\n", $aContent), ['href' => sprintf('/admin/%s', $module->name)]);
						$options = $isActive ? ['class' => 'active'] : [];
						$li[] = Html::tag('li', $a, $options);
					}
				}
			}

			if ($hasAnyItem == false)
			{
				array_pop($li);
			}
		}

		return Html::ul($li, ['class' => $this->defaultClassName, 'encode' => false]);
	}

}