<?php
/**
 * @user: Pawel Babilas
 * @date: 04.01.2016
 */

namespace app\common\widgets;


use yii\base\Widget;
use yii\helpers\Html;

class Menu extends Widget
{

//	public $options

	/**
	 * [
	 * 	name => link,
	 * 	name =>	[
	 * 			icon => iconSymbol,
	 *			url => link
	 * 		]
	 * ]
	 * @var array
	 */
	public $itemsList = [];

	/** @var string  */
	public $defaultIcon = 'hashtag';

	/** @var string  */
	public $defaultClassName = 'nav sidebar-menu';

	/** @var array  */
	public $options = [];

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
	}

	/**
	 * @return string
	 */
	public function run()
	{
		foreach ($this->itemsList as $name => $item)
		{
			if (is_array($item))
			{
				$icon = $item['icon'];
				$url = $item['url'];
			}
			else
			{
				$icon = $this->defaultIcon;
				$url = $item;;
			}

			$inner = Html::tag('i', Html::tag('span', ' '.$name), ['class' => "fa fa-$icon"]);
			$items[] = Html::a($inner, $url);
		}

		$class = isset($this->options['class']) ? $this->options['class'] : $this->defaultClassName;
		$this->options['class'] = $class;
		$this->options['itemOptions'] = ['class' => 'header'];

		return Html::ul($items, $this->options);
	}

}