<?php

namespace app\module\language\models;

use Yii;

/**
 * This is the model class for table "language".
 *
 * @property integer $id
 * @property string $name
 * @property string $symbol
 */
class Language extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'language';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 100],
            [['symbol'], 'string', 'max' => 4]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'symbol' => 'Symbol',
        ];
    }

    /**
     * @inheritdoc
     * @return LanguageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new LanguageQuery(get_called_class());
    }

    /**
     * @return Language|null
     */
    public static function getDefault()
    {
        return Language::findOne(['default' => true]);
    }

    /**
     * @return bool
     */
    public function beforeValidate()
    {
        if (is_null(Language::getDefault()) == false)
        {
            $this->addError('default', '`language.default_already_exists`');
        }

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}
