<?php
/**
 * Created by PhpStorm.
 * User: Pawel
 * Date: 28.11.15
 * Time: 22:30
 */

namespace app\common;

use app\module\module\models\Module;
use app\module\module\models\ModuleQuery;
use Yii;
use yii\web\NotFoundHttpException;

abstract class AbstractAdminController extends AbstractController
{
	/** @var array  */
	public $menuItems = [];
	/** @var Module  */
	public $currentModule = null;

	public static $allowedControllerAction = [
		'user' => [
			'auth' => [
				'login',
				'index'
			]
		]
	];

	public function init()
	{
		$moduleName = $this->module->id;
		/** @var Module $module */
		$this->currentModule = Module::findOne(['name' => $moduleName]);

		if ($this->needAuthentication() == false)
		{
			return true;
		}

		if (\Yii::$app->user->isGuest)
		{
			\Yii::$app->user->setReturnUrl(\Yii::$app->request->url);
			$this->addMessage('user', 'restricted_area', Message::ALERT);
			$this->redirect('/admin/user/auth/login');
			return false;
		}

		$this->checkModuleAccess();
		$this->checkAdminAccess();

		/** @var Module $menuItem */
		foreach(ModuleQuery::findAllOrdered() as $menuItem)
		{
			$category = $menuItem->getCategory();
			$this->menuItems[$category->name][] = $menuItem;
		}

		\Yii::$app->layout = 'admin.tpl';
	}

	public function beforeAction($action)
	{
//		$this->checkAdminAccess();
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	/**
	 * @throws NotFoundHttpException
	 */
	private function checkModuleAccess()
	{
		$modulePermissionName = sprintf('access%s', ucfirst($this->module->id));
		if (\Yii::$app->user->can($modulePermissionName) == false)
		{
			throw new NotFoundHttpException('You are not authorized to access this area');
		}
	}

	/**
	 * @throws NotFoundHttpException
	 */
	private function checkAdminAccess()
	{

//		/**
//		 * New rbc feature to extend
//		 */
//		$modulePrivilegeName = sprintf('access%s', ucfirst($this->module->id));
//		if (Yii::$app->user->can($modulePrivilegeName) == false)
//		{
//			throw new NotFoundHttpException();
//		}
//
//		if ($this->currentModule->admin_access == false)
//		{
//			if (\Yii::$app->user->can('accessModule') == false)
//			{
//				throw new NotFoundHttpException('You are not authorized to access this area');
//			}
//		}
	}

	/**
	 * @param $moduleId
	 *
	 * @return bool
	 */
	private function getAdminControllers($moduleId)
	{
		$module = Yii::$app->getModule($moduleId);
		if (is_null($module))
		{
			return false;
		}

		$files = glob($module->getControllerPath().'/*AdminController.php');

		/** @var string $file */
		foreach($files as $file)
		{
			$className = basename($file, '.php');
			$reflectionClass = new \ReflectionClass($module->controllerNamespace . '\\' . $className);

			if($reflectionClass->isSubclassOf('app\common\AbstractController'))
			{
				if (count($files) == 1)
				{
					return true;
				}

				if ($reflectionClass->hasConstant('MENU_NAME'))
				{
					$controllers[] = $reflectionClass->getConstant('MENU_NAME');
				}
			}
		}


		return isset($controllers) ? $controllers : false;
	}

	/**
	 * @return bool
	 */
	private function needAuthentication()
	{
		if (isset(AbstractAdminController::$allowedControllerAction[$this->module->id]) == false)
		{
			return true;
		}

		$unauthorizedModuleControllers = AbstractAdminController::$allowedControllerAction[$this->module->id];

		if (isset($unauthorizedModuleControllers[$this->id]) == false)
		{
			return true;
		}

		return false;
	}

	/**
	 * @return bool
	 */
	public function showInNav()
	{
		return true;
	}

}